import { useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import {
  TEMPLATES,
  buildExcelDocument,
  buildWordDocument,
  buildPdfDocument,
} from "./documentGenerator";

export default function DocumentModal({ isOpen, onClose, onDocumentGenerated }) {
  const [selectedFormat, setSelectedFormat] = useState("xlsx");
  const [selectedTemplate, setSelectedTemplate] = useState("budget_tracker");
  const [customTitle, setCustomTitle] = useState("");
  const [customFilename, setCustomFilename] = useState("");
  const [generating, setGenerating] = useState(false);
  const [statusMsg, setStatusMsg] = useState(null);

  if (!isOpen) return null;

  const handleGenerate = async () => {
    setGenerating(true);
    setStatusMsg("Building native document binary...");

    try {
      let docResult;

      if (selectedTemplate && TEMPLATES[selectedTemplate]) {
        // Build preset template
        docResult = await TEMPLATES[selectedTemplate].build();
      } else {
        // Build custom format
        const title = customTitle.trim() || "Orion Document";
        const fname = customFilename.trim() || `Orion_${Date.now()}`;

        if (selectedFormat === "xlsx") {
          docResult = await buildExcelDocument({
            filename: fname,
            title,
            sheetName: "Data",
            columns: [
              { header: "Item Description", key: "desc" },
              { header: "Category", key: "cat" },
              { header: "Amount", key: "amt", format: "currency", total: "sum" },
            ],
            rows: [
              ["Standard Operational License", "Software", 1200],
              ["Local Workstation Hardware", "Hardware", 4500],
              ["Compliance Audit Filing", "Legal", 850],
            ],
            showTotals: true,
          });
        } else if (selectedFormat === "docx") {
          docResult = await buildWordDocument({
            filename: fname,
            title,
            subtitle: "Generated by Orion Sovereign Edge AI",
            sections: [
              {
                heading: "1. Overview",
                paragraphs: [
                  "This document was generated locally by Orion with zero network egress.",
                ],
                callout: "All calculations, styling, and metadata were compiled on-device.",
              },
            ],
          });
        } else {
          docResult = await buildPdfDocument({
            filename: fname,
            title,
            subtitle: "Orion Sovereign AI Report",
            sections: [
              {
                heading: "1. Executive Summary",
                paragraphs: [
                  "Air-gapped document generated natively with zero cloud data transmission.",
                ],
              },
            ],
          });
        }
      }

      setStatusMsg("Saving document locally via Capability Broker...");

      // Save to local disk via Tauri IPC
      const savedDoc = await invoke("save_generated_document", {
        filename: docResult.filename,
        dataBase64: docResult.base64,
        fileType: docResult.fileType,
      });

      // Pass full doc with base64 so in-browser download copy works too
      const fullDoc = {
        ...savedDoc,
        base64: docResult.base64,
      };

      if (onDocumentGenerated) {
        onDocumentGenerated(fullDoc);
      }

      onClose();
    } catch (err) {
      console.error("Document generation failed:", err);
      setStatusMsg(`Error: ${err}`);
      setTimeout(() => setStatusMsg(null), 4000);
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="doc-modal-backdrop" onClick={onClose}>
      <div
        className="doc-modal-dialog"
        onClick={(e) => e.stopPropagation()}
        role="dialog"
        aria-modal="true"
      >
        <div className="doc-modal-header">
          <div className="doc-modal-title-group">
            <span className="doc-modal-icon">📄</span>
            <div>
              <h3>Generate Native Document</h3>
              <p className="doc-modal-sub">
                100% offline generation • Zero cloud transmission
              </p>
            </div>
          </div>
          <button
            type="button"
            className="doc-modal-close-btn"
            onClick={onClose}
          >
            ✕
          </button>
        </div>

        <div className="doc-modal-body">
          {/* Format Selector */}
          <div className="doc-format-selector">
            <div
              className={`doc-format-card ${selectedFormat === "xlsx" ? "active excel" : ""}`}
              onClick={() => {
                setSelectedFormat("xlsx");
                setSelectedTemplate("budget_tracker");
              }}
            >
              <span className="format-emoji">📊</span>
              <div className="format-name">Microsoft Excel</div>
              <div className="format-ext">.xlsx</div>
              <div className="format-desc">Formulas, tables, auto-widths</div>
            </div>

            <div
              className={`doc-format-card ${selectedFormat === "docx" ? "active word" : ""}`}
              onClick={() => {
                setSelectedFormat("docx");
                setSelectedTemplate("project_proposal");
              }}
            >
              <span className="format-emoji">📄</span>
              <div className="format-name">Microsoft Word</div>
              <div className="format-ext">.docx</div>
              <div className="format-desc">Styles, headings, callout boxes</div>
            </div>

            <div
              className={`doc-format-card ${selectedFormat === "pdf" ? "active pdf" : ""}`}
              onClick={() => {
                setSelectedFormat("pdf");
                setSelectedTemplate("executive_report");
              }}
            >
              <span className="format-emoji">📑</span>
              <div className="format-name">Adobe PDF</div>
              <div className="format-ext">.pdf</div>
              <div className="format-desc">Vector layout, headers & footers</div>
            </div>
          </div>

          {/* Template Choice */}
          <div className="doc-template-section">
            <div className="doc-section-title">Ready-Made Templates</div>
            <div className="doc-template-list">
              {Object.entries(TEMPLATES)
                .filter(([_, t]) => t.format === selectedFormat)
                .map(([key, t]) => (
                  <div
                    key={key}
                    className={`doc-template-option ${selectedTemplate === key ? "selected" : ""}`}
                    onClick={() => setSelectedTemplate(key)}
                  >
                    <div className="template-name">{t.name}</div>
                    <div className="template-desc">{t.description}</div>
                  </div>
                ))}

              <div
                className={`doc-template-option ${selectedTemplate === null ? "selected" : ""}`}
                onClick={() => setSelectedTemplate(null)}
              >
                <div className="template-name">Custom Document</div>
                <div className="template-desc">
                  Specify your own title and filename
                </div>
              </div>
            </div>
          </div>

          {/* Custom Details if Custom is selected */}
          {selectedTemplate === null && (
            <div className="doc-custom-fields">
              <div className="doc-field-group">
                <label>Document Title</label>
                <input
                  type="text"
                  placeholder="e.g. Q1 Expense Breakdown"
                  value={customTitle}
                  onChange={(e) => setCustomTitle(e.target.value)}
                  className="doc-modal-input"
                />
              </div>
              <div className="doc-field-group">
                <label>File Name</label>
                <input
                  type="text"
                  placeholder={`e.g. Report.${selectedFormat}`}
                  value={customFilename}
                  onChange={(e) => setCustomFilename(e.target.value)}
                  className="doc-modal-input"
                />
              </div>
            </div>
          )}

          {statusMsg && (
            <div className="doc-status-banner">
              <span className="doc-status-spinner">⚡</span>
              <span>{statusMsg}</span>
            </div>
          )}
        </div>

        <div className="doc-modal-footer">
          <button
            type="button"
            className="btn-doc-cancel"
            onClick={onClose}
            disabled={generating}
          >
            Cancel
          </button>
          <button
            type="button"
            className="btn-doc-generate-confirm"
            onClick={handleGenerate}
            disabled={generating}
          >
            {generating ? "Generating…" : "Generate Document"}
          </button>
        </div>
      </div>
    </div>
  );
}
